### ISSUE TITLE
Nodejs 16 is deprecated

### ISSUE THREAD

**Issue by Hermanverschooten** [mpizenberg/elm-tooling-action#3]
I recently have been getting this warning:

Node.js 16 actions are deprecated. 
For more information see: https://github.blog/changelog/2023-09-22-github-actions-transitioning-from-node-16-to-node-20/

**Comment by mpizenberg** [comment]
Thanks for the note, a PR that updates everything is welcome :)

**Comment by mpizenberg** [comment]
PR #4 merged and new version is published as v1.6 https://github.com/mpizenberg/elm-tooling-action/releases/tag/v1.6
Thank you!
